### ISSUE TITLE
Pod won't update

### ISSUE THREAD

**Issue by vjoomens** [matrix-org/matrix-ios-sdk#1031]
Hi, I've recently updated my swift project to 5.3, but for some reason the matrix sdk is stuck on 0.17.4. I've tried lots of things, like removing it, re-adding the pod, clearing pod caches, removing all pods and reinstalling them, but to no avail. Any pointers here?

**Comment by manuroe** [comment]
Are you stuck in this version because of you Podfile.lock?

There should be no relationships between CocoadPods and the swift version you use in your project.

You should play with those commands to debug your issue:
````
$pod search MatrixSDK
$pod repo update
$pod update MatrixSDK

**Comment by vjoomens** [comment]
@manuroe the solution was really simple, I just had to remove the SwiftSupport in the Podfile.
