### ISSUE TITLE
MXUser.updateWithRoomMemberEvent doesn't check for nil

### ISSUE THREAD

**Issue by cvwright** [matrix-org/matrix-ios-sdk#1045]
**Describe the bug**
`MXUser.updateWithRoomMemberEvent()` updates an `MXUser`'s displayname and avatarUrl from a `m.room.member` event.  But this code doesn't check whether the name and avatar in the event's `MXRoomMember` structure are nil.  Processing an event with nil's can cause the SDK to throw away valid profile data that it had before the event.

This is especially problematic on a homeserver that limits profile information to only those users who already share rooms.

For example:
* Suppose User A and User B don't belong to any rooms in common, but User A and User C are in one room (\#Room1) together, and User B and User C are in a different room (\#Room2) together.
* Then User A invites User B to join \#Room1.
* The `m.room.member` event will necessarily be missing the displayname and avatarUrl, because User A isn't allowed to see that information yet.
* When User C's client processes the `m.room.member event`, it nulls out User B's displayname and avatarUrl.  This impacts the way User C sees User B in both \#Room1 and \#Room2.

To make things even weirder, this can happen long after the original event, when User C is paginating back through old history in \#Room1.  As soon as his client processes the event, suddenly User B seems to lose his displayname and avatar everywhere.

**To Reproduce**
1. Log in three users User A, User B, and User C
2. User B: Set displayname and avatarUrl to normal, non-nil values
3. User C: Verify that the `MXUser` for User B shows the name and avatar that User B just set
4. User A: Send an `m.room.member` event for User B, with no displayname and no avatarUrl.
5. User C: Load the messages in the room where the event was sent.
6. User C: Look at the `MXUser` for User B.  See that the displayname and avatarUrl have been blown away.

**Expected behavior**
User B should have retained the displayname and avatar from before the `m.room.member` event.

**Smartphone (please complete the following information):**
 - Device: iPhone simulator
 - OS: iOS 14.4
 - SDK version: 0.17.4 (but code is unchanged in git as of this writing)

**Additional context**
This also raises a broader question about how `m.room.member` events should be handled when back paginating.  Even if the displayname and avatarUrl in the event are not nil, do I really want to replace User B's current name and avatar with one that might be several months (or more) out of date?

**Comment by manuroe** [comment]
Fixed by https://github.com/matrix-org/matrix-ios-sdk/pull/1060
