### ISSUE TITLE
Allow custom HTTP headers on registration and login

### ISSUE THREAD

**Issue by tladesignz** [matrix-org/matrix-ios-sdk#1184]
**Is your feature request related to a problem? Please describe.**

We currently run federated servers for a very vulnerable audience.

We want to be a good citizen in the fediverse, so we want to stop spammers from using our
systems.

The currently available solutions have the following problems for us:

1. We don't want to sell our audience to Google via Recaptcha.
2. They're not English speakers, might not even understand latin scripture, therefore will have problems filling that captcha anyway.
3. We don't want to make them give us any identifying things like phone numbers or mail addresses to keep them safe.

**Describe the solution you'd like**

In order to sort out spam bots on our servers, we like our client apps to send an API key
on registration via HTTP headers.

We're not interested in supporting other clients than our own, but we want to stay federated.

I'll send a PR with the code changes we need to make this happen.

**Describe alternatives you've considered**

We'd really hate to maintain patches on our own.

Other workarounds would need to make use of reflection (aka Objective-C-KVO) and a bunch of code duplication.

Another idea would be to add proprietary steps to the registration process. However, it seems, as pluggable, as the API design looks, Synapse isn't actually that pluggable in that regard.

Considering the imminent threat with spam bots, HTTP headers seem like a way quicker and more viable solution.

**Comment by pixlwave** [comment]
Hi @tladesignz, sorry about the delay, just looking into your issues now. Does the following setting fix this issue for you? https://github.com/matrix-org/matrix-ios-sdk/blob/d1b13303e281b9b7c59dff1205e7f13be53e776a/MatrixSDK/MXSDKOptions.h#L149

**Comment by tladesignz** [comment]
Thank you @pixlwave! I'll investigate this week and let you know!

**Comment by tladesignz** [comment]
@pixlwave, sorry for the delay.

Ok. That's quite interesting.

It seems to work.

However, *I have no clue, why*.

This option is only used in 2 places:

https://github.com/matrix-org/matrix-ios-sdk/blob/develop/MatrixSDK/Utils/MXHTTPClient.m#L663-L683

https://github.com/matrix-org/matrix-ios-sdk/blob/develop/MatrixSDK/Utils/Media/MXMediaLoader.m#L116-L151

`[MXHTTPClient setRequestParametersInJSON:]` seems not to get used anywhere.

How do these headers end up in every request?

And what's the analogon in the Android SDK2?

**Comment by pixlwave** [comment]
@tladesignz In the HTTP client it's set via the property in the init here: https://github.com/matrix-org/matrix-ios-sdk/blob/b094389f528604b54865f7e42c56f4d34eb81291/MatrixSDK/Utils/MXHTTPClient.m#L127

**Comment by tladesignz** [comment]
> @tladesignz In the HTTP client it's set via the property in the init here:
> 
> https://github.com/matrix-org/matrix-ios-sdk/blob/b094389f528604b54865f7e42c56f4d34eb81291/MatrixSDK/Utils/MXHTTPClient.m#L127

Aaaah. Excellently hidden! 😜 Thank you very much! Ok, so I'll close this issue and PR. It's obviously unnecessary.


> Re on Android, I've been told
> 
> > Not exactly in API. But you can add an interceptor (like the access token interceptor).
> 
> I hope this makes sense (I'm 100% uninformed on Kotlin 😅)

Oooh-ohh. I was afraid, that's going to be it. I already researched this once:

https://gitlab.com/keanuapp/keanuapp-ios/-/issues/236#note_645003296

I guess, I'll have to have a talk with your Android colleagues.


Thank you very much for your support, @pixlwave!

**Comment by tladesignz** [comment]
https://github.com/vector-im/element-android/issues/4724
