### ISSUE TITLE
Retry to-device messages

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-ios-sdk#1538]
Mirroring https://github.com/vector-im/element-web/issues/12851 from web: we should make sure that we retry to-device messages. New impl on web saves them in a queue to persistent storage to be sent when they can be.

**Comment by jdauphant** [comment]
Any news an when this will be implemented? 
This will have a major impact reducing on UTD ?

Cc @giomfo @phlniji

**Comment by BillCarsonFr** [comment]
Closing as it will be fixed by integrating rust SDK
