### ISSUE TITLE
Make Realm optional?

### ISSUE THREAD

**Issue by yspreen** [matrix-org/matrix-ios-sdk#1549]
Why would realm be a required dependency?

If I only want to use this project to interact with a homeserver, storing data with my own data model and storage, realm is a ton of dead weight. Making the app too big for an appclip as well. It would be amazing to have a version of the SDK that doesn't make assumptions about data storage! :)

**Comment by pixlwave** [comment]
There is some information about what the SDK uses caches for in this comment:
https://github.com/matrix-org/matrix-ios-sdk/issues/1497#issuecomment-1206320146

Realm is used for crypto and aggregations.

As the majority of our efforts for an iOS SDK are now focussed on https://github.com/matrix-org/matrix-rust-sdk, we're unlikely to find time to migrate to a different database, so I'm going to close this issue.

**Comment by yspreen** [comment]
@pixlwave  that sounds really cool, didn't know such a project existed!

Is it ready to be used in an iOS project in production? there doesn't seem to be much info about the use in iOS in the root readme. I'll investigate more

**Comment by pixlwave** [comment]
Ah, sorry, I should have linked you to the Swift build: https://github.com/matrix-org/matrix-rust-components-swift

Sadly, no it is not ready for production, it is still in a very early stage of development. It is however powering our early work on [ElementX](https://github.com/vector-im/element-x-ios).
