### ISSUE TITLE
Change verbosity of MXLog

### ISSUE THREAD

**Issue by yspreen** [matrix-org/matrix-ios-sdk#1550]
I have

```
        var config = MXLogConfiguration()
        config.logLevel = .none
        MXLog.configure(config)
```

before calling any MatrixSDK methods. Still, I'm seeing tons of `MXSyncResponseFileStore`, `MXHTTPClient` and `MXFileStore` log outputs. How does one properly configure this?

**Comment by yspreen** [comment]
@pixlwave I actually ended up solving it by calling log() first, then setting the level. I think the first call to log() always overrode the config. the PR you merged seems to indicate the reverse solution?

**Comment by pixlwave** [comment]
Ohhh interesting. I came to that conclusion because in Element, there's a call to `log` *before* the configuration is set. So when you tried setting `.none` it would never remove the destinations.

**Comment by yspreen** [comment]
well I actually chose error now. what I had to do to fix this bug where it was always verbose was to just add a printout before. so this is my appdelegate launch method now:

```
        MXLog.debug("Bonjour")
        let config = MXLogConfiguration()
        config.logLevel = .error
        MXLog.configure(config)
```
