### ISSUE TITLE
Track Edits

### ISSUE THREAD

**Issue by yspreen** [matrix-org/matrix-ios-sdk#1554]
Is there a built-in method to track message editing through this SDK? Or do I have to replay the events applying the changes myself?

**Comment by pixlwave** [comment]
Edits are handled by `MXAggregatedEditsUpdater`. You can check an event's `contentHasBeenEdited` property to find out if it had been edited.

**Comment by yspreen** [comment]
I thought I had to track the edits by myself, applying the changes manually. but I guess the edit events are just so that you can show edits in the timeline and the original event will have been modified?

**Comment by pixlwave** [comment]
That is correct 👍
