### ISSUE TITLE
Consulting call in call transfer has no audio

### ISSUE THREAD

**Issue by simonwiedmer** [matrix-org/matrix-ios-sdk#1580]
In a setup with a sip bridge, there is no audio on the consulting call leg within a call transfer

* The element iOS client is active in foreground
* A call from a PSTN number (0797710405) via sip bridge is coming in and is accepted
* This call has good audio
* The user now presses the transfer button, putting the PSTN user on hold (hears hold music)
* The user dials a second PSTN number on the transfer dial pad and connects with “consult first” active
* The second PSTN user gets and accepts the call
* This consulting call has no audio at all

**Comment by manuroe** [comment]
https://github.com/matrix-org/matrix-ios-sdk/pull/1738 offers a way to fix it for matrix applications that need it.
