### ISSUE TITLE
MatrixKit (from `https://github.com/matrix-org/matrix-ios-kit.git`, branch `develop`) was resolved to 0.16.11, which depends on       MatrixSDK (= 0.20.13)

### ISSUE THREAD

**Issue by omershafique0** [matrix-org/matrix-ios-sdk#1786]
When trying to install MatrixKit with the latest MatrixSDK (0.26.10), pod installation gives error

**Comment by pixlwave** [comment]
As mentioned in the readme, MatrixKit is [deprecated](https://github.com/matrix-org/matrix-ios-kit#deprecated), so unfortunately we won't be able to provide support here.
