### ISSUE TITLE
No such module 'MatrixKit'

### ISSUE THREAD

**Issue by omershafique0** [matrix-org/matrix-ios-sdk#1792]
MatrixKit not installing with the latest 'MatrixSDK', '~> 0.26.10'
is there any to install MatrixKit with the latest MatrixSDK or any other way around how to use/bypass this in my project?

**Comment by pixlwave** [comment]
As mentioned in the readme, MatrixKit is [deprecated](https://github.com/matrix-org/matrix-ios-kit#deprecated), so unfortunately we won't be able to provide support here.
