### ISSUE TITLE
App crashing when trying to enable crypto

### ISSUE THREAD

**Issue by adp100** [matrix-org/matrix-ios-sdk#1802]
Team,

I am getting a crash when trying to enable crypto on iOS side using the SDK.

``` 
let credentials = MXCredentials(homeServer: "http://matrix.org",
                                userId: "@your_user_id:matrix.org",
                                accessToken: "your_access_token")
//Edit that resolved the first crash
credentials.deviceId = device_id

// Create a matrix client
let mxRestClient = MXRestClient(credentials: credentials, unrecognizedCertificateHandler: nil)

// Create a matrix session
let session = MXSession(matrixRestClient: mxRestClient) 

// enable crypto
if session.crypto == nil {
            session.enableCrypto(true) { response in
                if response.isSuccess {
                    print("crypto is enabled")
                } else {
                    print("something went wrong")
                }
            }
        }


```

This is the error getting printed when trying the above code.
[MXCryptoV2Factory] buildCrypto(session:migrationProgress:success:failure:): Missing required dependencies

Is there a way to resolve this issue. I am new to matrix. If the above process is not right can an example code be provided for the same.

Thanks.

**Comment by adp100** [comment]
Found the issue, credentais was missing the device_id value. after providing it, the app crashing was resolved and it is happening at a new place at MXKeyProvider.m file. 
The crash is :
 **Terminating app due to uncaught exception 'MandatoryKey', reason: 'No key value for mandatory Key (data type : org.matrix.sdk.crypto.store.key)'** 
Am I missing anything 
Is there anything to be done to resolve this issue.

**Comment by mehroozkhan50** [comment]
How you fix it

> Found the issue, credentais was missing the device_id value. after providing it, the app crashing was resolved and it is happening at a new place at MXKeyProvider.m file.
> The crash is :
> **Terminating app due to uncaught exception 'MandatoryKey', reason: 'No key value for mandatory Key (data type : org.matrix.sdk.crypto.store.key)'**
> Am I missing anything here like above?
> Is there anything to be done to resolve this issue.

How you fix it? how to add device_id value?

**Comment by adp100** [comment]
@mehroozkhan50 I edited my question to add it. 

let credentials = MXCredentials(homeServer: "http://matrix.org",
                                userId: "@your_user_id:matrix.org",
                                accessToken: "your_access_token")
//Edit that resolved the first crash
credentials.deviceId = device_id

we get the device id when we login.

**Comment by Kn3cht** [comment]
> How you fix it
> 
> > Found the issue, credentais was missing the device_id value. after providing it, the app crashing was resolved and it is happening at a new place at MXKeyProvider.m file.
> > The crash is :
> > **Terminating app due to uncaught exception 'MandatoryKey', reason: 'No key value for mandatory Key (data type : org.matrix.sdk.crypto.store.key)'**
> > Am I missing anything here like above?
> > Is there anything to be done to resolve this issue.
> 
> How you fix it? how to add device_id value?

Having the same issue. Any updates on this?

**Comment by mehroozkhan50** [comment]
@Kn3cht issue was resolved

**Comment by Kn3cht** [comment]
> @Kn3cht issue was resolved

I'm referring to the followup issue: Terminating app due to uncaught exception 'MandatoryKey', reason: 'No key value for mandatory Key (data type : org.matrix.sdk.crypto.store.key)'

**Comment by andrii-drobiazko** [comment]
Having the same issue, self.delegate is nil

**Comment by andrii-qunicate** [comment]
Having the same issue, `self.delegate` is nil

**Comment by AlvaroSanzRodrigo** [comment]
Hi! know this is old but, any of you got a solution? I'm unable to find a way to make this work...

**Comment by rahulchops93** [comment]
Hi! Can anyone help me out to connect call? Right now capture session is started but camera preview not showing on view.


```
class ViewController: UIViewController {
    @IBOutlet weak var localView        : UIView!
    let callStack       = MXJingleCallStack()
    var accessToken     : String = ""
    var session         : MXSession!
    var activeCall            : MXCall!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        MXLogger.setSubLogName("MatrixCall")
        PermissionHandler.shared.requestCameraMicrophone()
        
        
        let credentials = MXCredentials(homeServer: "",
                                        userId: ""
                                        accessToken: accessToken)
        credentials.deviceId = "isthisdeviceid"
        
        let rest = MXRestClient(credentials: credentials)
        session = MXSession(matrixRestClient: rest)
        
        // Set up the store
        let store = MXFileStore()
        session.setStore(store, completion: { response in
            switch response {
            case .success:
                print("Store set successfully")
                self.startSession()
            case .failure(let error):
                print("Failed to set store: \(error.localizedDescription)")
            }
        })
    }
    
    func startSession() {
        session.start(completion: { response in
            switch response {
            case .success(_):
                print("====== **** Matrix session started successfully. ****")
                self.session.enableVoIP(with: self.callStack)
            case .failure(let err):
                print("====== Error starting session: \(err.localizedDescription)")
            }
        })
    }
    
    @IBAction func openCallView(sender: Any?) {
        self.startCall()
    }
    
    func startCall() {
        let room = session.room(withRoomId: "")
        
        let config = MXCallKitConfiguration(name: "Abc", ringtoneName: nil, iconName: nil, supportsVideo: true)
        let callkit = MXCallKitAdapter(configuration: config)
        session.callManager.callKitAdapter = callkit
        if let callSt = session.callManager.callStack.createCall() as? MXJingleCallStackCall {
            callSt.selfVideoView = self.view
            callSt.remoteVideoView = localView

            self.startCapture(callSt: callSt)
            self.session.callManager.placeCall(inRoom: "!SotimBOIOGbhreOWRd:matrix.org", withVideo: true) { call in
                print("=== *** Call success")
                self.activeCall = call
                call.audioMuted = false
                call.videoMuted = false
            } failure: { error in
                print("=== **** \(error)")
            }
            
        }
    }
    
    func startCapture(callSt: MXJingleCallStackCall) {
        callSt.startCapturingMedia(withVideo: true) {
            print("startCapturingMedia success")
        } failure: { error in
            print("startCapturingMedia unsuccess: \(error)")
        }
    }
}
```
