### ISSUE TITLE
Info.plist based SSL pinning

### ISSUE THREAD

**Issue by herpiko** [matrix-org/matrix-ios-sdk#1804]
Hi @giomfo 

I stumbled upon your [pull request](https://github.com/matrix-org/matrix-ios-sdk/pull/662). I tried to set a self-signed CA in my `Info.plist` but it still failed to recognize the CA.

![Untitled](https://github.com/matrix-org/matrix-ios-sdk/assets/2534060/325f56d8-96e0-4e9a-ba1a-2dfd3483db7e)

Do you any example how to use a pinned certificate?

**Comment by giomfo** [comment]
@herpiko Hi, you just need to add in the assets of the Xcode project the certificate (to trigger this [line](https://github.com/matrix-org/matrix-ios-sdk/pull/662/files#diff-16d9586a8c9f5d19d3e686e732314d7076b22ea723de89721da049fb9dc7c9aaR751) with the certificate to pin)

**Comment by NicolasBuquet** [comment]
SSL pinning by embedding in ther assets of the project does not work for third party frameworks that doesn't rely on AFNetworking.
MapLibre for instance won't use the certificate pinning this way.
If certificate pinning was implemented as @herpiko said, MapLibre would respect certificate pinning.

Certificate pinning should be implemented using `NSApptransportSecurity` as it is done Android side.

**Comment by giomfo** [comment]
@NicolasBuquet is right. The correct way to handle certificate pinning is to use `NSApptransportSecurity`.
@herpiko: [my PR](https://github.com/matrix-org/matrix-ios-sdk/pull/662) is not relevant anymore. It should be ignored by removing any certificate from the assets
