### ISSUE TITLE
Swift version?

### ISSUE THREAD

**Issue by gperdomor** [matrix-org/matrix-ios-sdk#183]
Hi...

Do you plan release a Swift version of the SDK?

Thanks

**Comment by manuroe** [comment]
No, not it short term.
We are focused on improving the existing code.

**Comment by manuroe** [comment]
Thanks to @aapierce0 , there is now some Swift APIs for the SDK.
There is also a brand new pod dedicated to Swift: [SwiftMatrixSDK](https://cocoapods.org/pods/SwiftMatrixSDK).

**Comment by gperdomor** [comment]
@manuroe this week i started a new project to map all endpoints of matrix using Swift and Moya, the main idea is build a rest client which can be evolve in a SDK... This is my project https://github.com/gperdomor/matrix-swift-sdk
