### ISSUE TITLE
Unable to receive m.receipt event

### ISSUE THREAD

**Issue by krissirk0906** [matrix-org/matrix-ios-sdk#1886]
Im using the newest version of Matrix ios sdk (v0.27.15) and can not receive any receipt event in my room.

**Comment by AmanGupta-Stackflow** [comment]
Can you share the code. How did you achieve receipt event. @krissirk0906

**Comment by krissirk0906** [comment]
@AmanGupta-Stackflow you should follow the guide in [Use case #2](https://github.com/matrix-org/matrix-ios-sdk?tab=readme-ov-file#use-case-2-bis-get-the-rooms-the-user-has-interacted-with-using-a-permanent-mxstore). I don't know why but we can only get the receipt event from the stored room.

**Comment by AmanGupta-Stackflow** [comment]
@krissirk0906 
Thanks for your reply. When i'm adding store then i'm getting another crash
[MXClientInformationService] No device id

Session is returning device Id as nil //Class Name: public class MXClientInformationService
//session.myDeviceId

Can you help with that?

**Comment by krissirk0906** [comment]
@AmanGupta-Stackflow Sorry, I have not meet this bug yet

**Comment by AmanGupta-Stackflow** [comment]
Okay, @krissirk0906 
Is that possible if you can share your code for setting up store? because i'm getting crash while adding store.

**Comment by krissirk0906** [comment]
This is my code for setting store @AmanGupta-Stackflow 

```
DispatchQueue.main.async {
      let mxSession = MXSession(matrixRestClient: mxRestClient)
     
      if let mxSession = mxSession {
        self.session = mxSession
        let store = MXFileStore()
        mxSession.setStore(store) {  response in
          guard response.isSuccess else { return }
          // Launch mxSession: it will first make an initial sync with the homeserver
          mxSession.start { response in
            guard response.isSuccess else { return }
    
              // mxSession is ready to be used
              // now we can get all rooms with:
              session.listenToEvents([.roomMessage, .roomCreate]) { event, direction, roomState in
                if direction == .forwards {
                    //handle new event here
                }
            }
          }
          
        }
      }
}
```

**Comment by AmanGupta-Stackflow** [comment]
@krissirk0906 
I'm using the same code but facing issues. Its working fine  when app is freshly installed in device. But crashing when running again in device. 
Crash is due to session UserID and Session DeviceID. 
Do you have any idea for this?

**Comment by krissirk0906** [comment]
@AmanGupta-Stackflow Matrix save your session of your previous login. Make sure you have check the last session of Matrix before login to the new account. I think this make ur app crash =))

**Comment by AmanGupta-Stackflow** [comment]
@krissirk0906 
Thanks for your inputs. I will check and get back to you if any issues occurs.
