### ISSUE TITLE
"duplicate symbol" error when using both OLMKit & use_frameworks in podfile

### ISSUE THREAD

**Issue by aapierce0** [matrix-org/matrix-ios-sdk#219]
An error message occurs when trying to compile a project that uses `pod 'MatrixSDK'`, `pod 'OLMKit'`, and `use_frameworks!` in the podfile.

```
duplicate symbol _OLMKitVersionString in:
    [...]/Build/Intermediates/Pods.build/Debug-iphonesimulator/OLMKit.build/Objects-normal/x86_64/OLMKit.o
    [...]/Build/Intermediates/Pods.build/Debug-iphonesimulator/OLMKit.build/Objects-normal/x86_64/OLMKit_vers.o
ld: 1 duplicate symbol for architecture x86_64
```

In order for the pods to be visible to Swift, `use_frameworks!` must be set.

I created a two simple demo projects that illustrate this error – one in Obj-C and one in Swift (the projects do pretty much the same thing)

https://github.com/aapierce0/Dummy-Matrix-Client-Objc
https://github.com/aapierce0/Dummy-Matrix-Client-Swift

**Comment by manuroe** [comment]
Thank you very much for such good detailed issue. 
I am a bit surprised that it leads to a duplicate symbol but I am going to check it with your demo projects.

**Comment by manuroe** [comment]
I guess turning on ```use_frameworks!```  enables the auto-generation of a VersionString for OLMKit in this new OLMKit_vers.c file which conflicts with the existing one.

Namespacing the version into the OLMKit class as you did in your PR is the best solution.
