### ISSUE TITLE
MXCrypto: app may crash on clear cache because of the periodic uploadKeys

### ISSUE THREAD

**Issue by giomfo** [matrix-org/matrix-ios-sdk#234]

**Comment by giomfo** [comment]
4744023655241328129 - 2017-02-13 10:04:18 +0000
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
Application: Vector (im.vector.app)
Application version: 0.3.9 (r57)
Matrix SDK version: 0.7.7
Build: master #57
iPhone 10.2.1

Main thread: YES
(
	0   CoreFoundation                      0x00000001903011d0 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018ed3855c objc_exception_throw + 56
	2   CoreFoundation                      0x00000001901e4eac <redacted> + 364
	3   CoreFoundation                      0x00000001901e4d1c <redacted> + 64
	4   Vector                              0x00000001002de428 Vector + 2155560
 -> -[MXCrypto uploadDeviceKeys:failure:] (in Vector) (MXCrypto.m:1764)
	5   Vector                              0x00000001002d9290 Vector + 2134672
 -> -[MXCrypto uploadKeys:success:failure:] (in Vector) (MXCrypto.m:842)
	6   Vector                              0x00000001002d9500 Vector + 2135296
 -> -[MXCrypto uploadKeys] (in Vector) (MXCrypto.m:911)
	7   Foundation                          0x0000000190e162e4 __NSFireTimer + 88
	8   CoreFoundation                      0x00000001902af1d8 <redacted> + 28
	9   CoreFoundation                      0x00000001902aeeec <redacted> + 872
	10  CoreFoundation                      0x00000001902ae7a8 <redacted> + 244
	11  CoreFoundation                      0x00000001902ac3a4 <redacted> + 1572
	12  CoreFoundation                      0x00000001901da2b8 CFRunLoopRunSpecific + 444
	13  GraphicsServices                    0x0000000191c8e198 GSEventRunModal + 180
	14  UIKit                               0x00000001962217fc <redacted> + 684
	15  UIKit                               0x000000019621c534 UIApplicationMain + 208
	16  Vector                              0x0000000100113b78 Vector + 277368
 -> main (in Vector) (main.m:30)
	17  libdyld.dylib                       0x000000018f1bd5b8 <redacted> + 4
)

**Comment by manuroe** [comment]
The crash occurred on a state event redaction which leads to a *room initial sync* request but it was the Monday morning when the *room initial sync* API was disabled on matrix.org hs.
In this situation, the sdk sends kMXSessionDidCorruptDataNotification. 

When this happens during an initialSync, the notification can be sent before the crypto was started. Here is the race condition.
