### ISSUE TITLE
[MXSession resetRoomsSummariesLastMessage] freezes the app

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-ios-sdk#292]
In https://github.com/matrix-org/riot-ios-rageshakes/issues/19, the system detects a time change (which is unexpected) which leads to the call of [MXSession resetRoomsSummariesLastMessage] that seems to freeze the app.

This call also generates a unexpected load of [MXFileStore commit] whereas only one should do the job.

**Comment by giomfo** [comment]
done
