### ISSUE TITLE
Add WebRTC sample app using OpenWebRTC 

### ISSUE THREAD

**Issue by stefanalund** [matrix-org/matrix-ios-sdk#3]
Add a sample app with WebRTC capabilities using OpenWebRTC: https://github.com/EricssonResearch/openwebrtc

Would it be a new app or added functionality to the existing one?

**Comment by stefanalund** [comment]
Addressed by https://github.com/matrix-org/matrix-ios-sdk/pull/9

**Comment by manuroe** [comment]
OpenWebRTC can be added to a matrix app thanks to https://github.com/matrix-org/matrix-ios-openwebrtc-wrapper
The pod is MatrixOpenWebRTCWrapper

**Comment by stefanalund** [comment]
Very nice! Great work.
