### ISSUE TITLE
MXJingleCallStackCall's createLocalMediaStream method freezes

### ISSUE THREAD

**Issue by anuj-gola** [matrix-org/matrix-ios-sdk#382]
Hi,

I am using Matrix SDK framework using Pods in iOS and the version is "0.9.2".

Description of the issue:
Once I start a video call it works as expected but for consecutive calls,  when MXJingleCallStackCall's createLocalMediaStream is called, it calls RTCPeerConnectionFactory class's method avFoundationVideoSourceWithConstraints which freezes for almost 15 seconds and then returns the video source. 'nil' is passed as its argument, I am not sure what causes this issue.

What is the expected result?
RTCPeerConnectionFactory class's method avFoundationVideoSourceWithConstraints should not freeze.

What do you see instead?
UI hangs on video call once RTCPeerConnectionFactory class's method avFoundationVideoSourceWithConstraints is called but not for first time.

Please look into it and provide a solution asap for the same.

Thanks in advance.

**Comment by manuroe** [comment]
Fixed on develop (https://github.com/matrix-org/matrix-ios-sdk/commit/4165e16)

**Comment by anuj-gola** [comment]
Thanks you so much, that resolved the issue.
