### ISSUE TITLE
cannot convert call result type '(_)->Void' to expected '(()->Void)!'

### ISSUE THREAD

**Issue by Bleiki** [matrix-org/matrix-ios-sdk#393]
At compilation produces 76 errors of type:  cannot convert call result type '(_)->Void' to expected '(()->Void)!'. iOS 11.

**Comment by manuroe** [comment]
Could you give us more details? What are you doing to get this errors?

As long as ```pod lib lint --allow-warnings``` on our pods returns no errors, things are right in our side.

**Comment by Bleiki** [comment]
I'm create project, add Podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

def pods

pod 'SwiftMatrixSDK'

end

target 'VistaChat' do
pods
end

Then i go to еру terminal and prescribe pod install.
Then i open .xcworkspace, compile a project and get this errors.

**Comment by Bleiki** [comment]
I'm getting this error in the method "@nonobjc @discardableResult func resetPaginationAroundInitialEvent(withLimit limit: UInt, completion: @escaping (_ response: MXResponse<Void>) -> Void) -> MXHTTPOperation {
        return __resetPaginationAroundInitialEvent(withLimit: limit, success: currySuccess(completion), failure: curryFailure(completion))" for  currySuccess(completion).

**Comment by biswapratik88** [comment]
I am also getting the same issue. Any updates on the solution??

**Comment by mmuharem** [comment]
SwiftMatrixSDK doesn't work for swift 4.

My solution was to use the swift 3.2 version. 

I did this by selecting pods in the Xcode project explorer, SwiftMatrixSDK in the target, selecting 'Build Settings' and then choosing Swift 3.2 in the 'Swift Compiler - Language'

**Comment by manuroe** [comment]
> SwiftMatrixSDK doesn't work for swift 4.

True. This is the problem. 
`pod lib lint --allow-warnings` works when running in the sdk folder because we have a `.swift-version` file pointing to swift 3.2.

If someone is strong enough in swift to convert the `currySuccess` template method in swift 4, the help will be much appreciated.
