### ISSUE TITLE
no such module "SwiftMatrixSDK"

### ISSUE THREAD

**Issue by talalt** [matrix-org/matrix-ios-sdk#406]
Hello matrix team.
My XCode doesn't recognize "SwiftMatrixSDK", we added "pod SwiftMatrixSDK" into Podfile. 
Swift version 4. 
XCode version 9.0. 
Thank you.

**Comment by kriti-singla** [comment]
Facing same issue. Is there solution for this issue?

**Comment by manuroe** [comment]
Should be fixed with #463.
