### ISSUE TITLE
Will Matrix iOS support FCM instead of APNS

### ISSUE THREAD

**Issue by supritpatra** [matrix-org/matrix-ios-sdk#434]
We have implemented FCM for sending Push Notifications for our Android and iOS App. Is there a way Matrix can support FCM instead of APNS? Is it something that is in the works?

**Comment by manuroe** [comment]
This is certainly possible but I do not think it was already done. @dbkr?
I can only say that this is not in the road map of the core team. As usual, PRs are welcome.
However, it would be better to check that in https://github.com/matrix-org/sygnal.

**Comment by dbkr** [comment]
Firebase is just a wrapper around iOS push, so it shouldn't really be necessary to support Firebase explicitly in the iOS SDK. If you want to send additional push to your app with Firebase, you can probably do it by importing the existing push token into firebase.
