### ISSUE TITLE
Public Rooms GET Request

### ISSUE THREAD

**Issue by mmuharem** [matrix-org/matrix-ios-sdk#437]
I am doing something like the example shown to get public rooms:

`mxRestClient.publicRooms { response in`
   ` switch response {`
   ` case .success(let rooms):`

        `// rooms is an array of MXPublicRoom objects containing information like room id`
        print("The public rooms are: \(rooms)")

   ` case .failure: break`
   `         }`
`}`

But when it comes to using this function, Xcode is not allowing `mxRestClient.publicRooms `without parameters, ie, the image below
![screen shot 2017-12-20 at 2 02 10 pm](https://user-images.githubusercontent.com/6509420/34223744-71c589a0-e58e-11e7-988f-8242e2b5f9f2.png)

The problem then becomes that `publicRoomsOnServer` function in `MXRestClient` is doing a filter on number of parameters in the function declaration (if ==0, do GET, else do POST), but there is no way to avoid it considering the parameters (server and limit) are not set to optionals. 

what does this mean:  
`// If there is no parameter, use the legacy API. It does not required an access token.?`

Any advice on this?

**Comment by mmuharem** [comment]
Any update on this?

**Comment by ahmedqandil** [comment]
Hello, We are facing the same issue. I see that the issue was closed. What was the solution to this?

**Comment by ahmedqandil** [comment]
@manuroe  can you please support on this?

**Comment by ahmedqandil** [comment]
@aapierce0 Hello, @manuroe informed us that you worked on the swift SDK for Matrix. We are facing a number of issues. Can you support us please?

We tried to build the bridge between obj-c and swift and we failed. Would you be able to help?
