### ISSUE TITLE
Pod install issue 

### ISSUE THREAD

**Issue by Sylar-zp** [matrix-org/matrix-ios-sdk#473]
When try start pod install with MatrixSDK & MatrixKit in pod file have to issue on "Installing cmark (0.24.1)" 

> [!] /bin/bash -c 
> set -e
> echo `pwd`
> sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
> mkdir -p build; cd build && cmake -G Xcode ..
> 
> 
> /Users/userName/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.1-ec027
> /bin/bash: line 4: cmake: command not found

Try to do all of the fixes that nothing help. Why can it be?  

If in pod file I have MatrixSDK & MatrixKit and I try start pod update I see this error 

> [!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

Reinstall CocoaPods and rebuild pod file and all that is connected with this not help.

**Comment by manuroe** [comment]
You need to install cmake. `brew install cmake` can be your friend.
Then, make a new `pod install`.
