### ISSUE TITLE
NS_REFINED_FOR_SWIFT

### ISSUE THREAD

**Issue by expertalex** [matrix-org/matrix-ios-sdk#488]
A lot of methods has the attribute NS_REFINED_FOR_SWIFT, it is really necessary...?
We are not using SwiftMatrixSDK because of several problems in this library.

**Comment by manuroe** [comment]
SwiftMatrixSDK has been brought by the community who knows better about Swift than the core team for the moment.
I just can say that `SwiftMatrixSDK` and its `NS_REFINED_FOR_SWIFT` was used in several projects.
