### ISSUE TITLE
Swiping room from Recents doesn't remove the room

### ISSUE THREAD

**Issue by stefanalund** [matrix-org/matrix-ios-sdk#5]
When I restart the app the room is still there. Looks like the server is not told about the removal (only the UITableView model?)

**Comment by stefanalund** [comment]
So the room is actually deleted from the server, but it still appears on the app that removed it. Could it be a caching problem?

**Comment by manuroe** [comment]
Yes. This is a cache issue. The deletion is not implemented at the MXFileStore level. I am fixing it.
Thanks for the report.

**Comment by manuroe** [comment]
The implementation was indeed here but with no test.
We have now a SDK test to prevent regression on this.

**Comment by stefanalund** [comment]
👍
