### ISSUE TITLE
"_OBJC_CLASS_$_MXJingleCallStack", referenced from

### ISSUE THREAD

**Issue by NijaahnandhRV** [matrix-org/matrix-ios-sdk#517]
I'm using matrix sdk for making call after installing a pod which is also used for calling it gives me an error that

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MXJingleCallStack", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by manuroe** [comment]
@NijaahnandhRV , can you post your podfile, please?

**Comment by NijaahnandhRV** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StarterKit



# Different flavours of pods to MatrixKit
# The tagged version on which this version of Vector has been built
pod 'MatrixKit', '0.3.19'

# The lastest release available on the CocoaPods repository 
#pod 'MatrixKit'

# The develop branch version
#pod 'MatrixSDK', :git => 'https://github.com/matrix-org/matrix-ios-sdk.git', :branch => 'develop'
#pod 'MatrixKit', :git => 'https://github.com/matrix-org/matrix-ios-kit.git', :branch => 'develop'

# The one used for developing both MatrixSDK and MatrixKit
# Note that MatrixSDK must be cloned into a folder called matrix-ios-sdk next to the MatrixKit folder
#pod 'MatrixKit', :path => '../matrix-ios-kit/MatrixKit.podspec'
#pod 'MatrixSDK', :path => '../matrix-ios-sdk/MatrixSDK.podspec'

pod 'GBDeviceInfo', '~> 4.1.0'

pod 'GoogleAnalytics'
# The Google WebRTC stack
pod 'WebRTC'
end

**Comment by NijaahnandhRV** [comment]
Hi @manuroe 

I have attached my podfile.

[Podfile.zip](https://github.com/matrix-org/matrix-ios-sdk/files/2126583/Podfile.zip)

**Comment by swbisoyi** [comment]
I'm having the same issue. Any solution?

**Comment by Maxim-Zakopaylov** [comment]
@swbisoyi can you solved this issue?

**Comment by ManiaChamp** [comment]
Any solution ,or you guys just closed it . Its still there
