### ISSUE TITLE
how to get the users access token

### ISSUE THREAD

**Issue by riobijanero** [matrix-org/matrix-ios-sdk#558]
to Get the rooms the user has interacted with, a user access token is required

how do I find out the user's access token?

**Comment by manuroe** [comment]
The access token is provided by the homeserver after login or registration operation (in `MXCredentials`). The app must store it safely and init `MXSession` or `MXRestClient` with it to get access to the user's data.

**Comment by adantenr** [comment]
An access token can be found in a Riot app after login.

In case of the Riot Web app, it's found under the 'Advanced' section of the 'Help & About' tap.

**Comment by smhk** [comment]
Thank you so much for that amazing tip, @adantenr  .
