### ISSUE TITLE
Room summary aliases = nil

### ISSUE THREAD

**Issue by vjoomens** [matrix-org/matrix-ios-sdk#788]
Hi, after server upgrade to 1.11.1 the Swift Matrix SDK returns nil on room.summary.aliases. After some debugging it seems that the server does return the m.room.aliases event type, but these event types don't show up in the SDK. Only the canonical alias is available. I'm using SDK version 0.15.2.

**Comment by manuroe** [comment]
Fixed in https://github.com/matrix-org/matrix-ios-sdk/pull/861/commits/1a543f5efc0a029cb2e8499a6ce2e3700e80c0a6.
