### ISSUE TITLE
Remove UIWebview dependency

### ISSUE THREAD

**Issue by david1hyman** [matrix-org/matrix-ios-sdk#793]
Everyone has been seeing this warning when uploading to AppStoreConnect:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

The Matrix SDK depends on AFNetworking which includes a category `UIWebview+AFNetworking`. After April 2020 this will prevent new apps from being submitted. In December Apple will block updates also (including updates to Riot).

Looks like work in progress here:
https://github.com/AFNetworking/AFNetworking/pull/4513

**Comment by hannojg** [comment]
Hey, when can we see this released? I see that this landed on the `xcode11` branch but is not yet in the development branch. I guess my company's app was today rejected due to this.

**Comment by alexeymilakhin** [comment]
@manuroe please, help

**Comment by david1hyman** [comment]
@hannojg in the meantime you can unblock your app submission by manually deleting `UIWebView+AFNetworking` from the AFNetworking pod. You might need to follow the compiler around to remove any dependencies in the pod itself. Of course you'll lose the change on a `pod install` but you will be able to get through App Store review in the meantime.

**Comment by hannojg** [comment]
@david1hyman thank you for pointing out this work around, will try it out!

**Comment by kiliankoe** [comment]
Thanks @david1hyman, that worked for me 👍 Definitely hoping for an upgrade of AFNetworking here as well 😊
