### ISSUE TITLE
pod install failed after adding SwiftMatrixSDK to Podfile

### ISSUE THREAD

**Issue by marcelkussin** [matrix-org/matrix-ios-sdk#795]
Hello everyone,

i just added the line 
```
pod 'SwiftMatrixSDK'
```
to the Podfile and then i do 

```
pod install
```

then i get the following error

```
The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `SwiftMatrixSDK` depends upon `AFNetworking`, `GZIP`, `OLMKit`, `Realm`, and `libbase58`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

I tried to add 'use_modular_headers!' to the Podfile then 'pod install' works but i get multiple errors while compiling the app
```
The following build commands failed:
	CompileC ... /ios/Pods/Folly/folly/Unicode.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by hannojg** [comment]
My workaround is to set `use_modular_headers!`globally in my Podfile and setting every other Pod to `:modular_headers => false`. 
Just setting `pod 'SwiftMatrixSDK', :modular_headers => true` didn't worked.

Super confused 😅

**Comment by hannojg** [comment]
Found a better workaround. I just learned that the Podspec file is just there to declare what it depends on, the "how" to include these dependencies is dependent on the project importing that pod. Thus we can define modular headers for all dependencies in our Podfile:

```
  pod 'AFNetworking', :modular_headers => true
  pod 'GZIP', :modular_headers => true
  pod 'OLMKit', :modular_headers => true
  pod 'Realm', :modular_headers => true
  pod 'libbase58', :modular_headers => true
  pod 'SwiftMatrixSDK', :modular_headers => true
```

**Comment by marcelkussin** [comment]
thanks, that worked for me
