### ISSUE TITLE
In Audio call device not ringing when try from real device 

### ISSUE THREAD

**Issue by muhammedm22** [matrix-org/matrix-ios-sdk#866]
I am trying to make an Audio call between device and simulator  it's ringing when i am trying to call a simulator but when call real device the ringing tone is silent but Video call is working fine .

**Comment by maulikgoyanidbc** [comment]
> I am trying to make an Audio call between device and simulator it's ringing when i am trying to call a simulator but when call real device the ringing tone is silent but Video call is working fine .

HI @muhammedm22 
I want to make audio call. can you provide code or documentation for that? Your help will boost in our development. Appreciated 
Thank you
