### ISSUE TITLE
Include LatestRoomState in MXRoomSummary

### ISSUE THREAD

**Issue by lampholder** [matrix-org/matrix-ios-sdk#876]
We need to know the canonicalAlias from MXRoomSummary object.

This information (canonicalAlias) is in the MXRoomState class. The problem is that to obtain the canonicalAlias we need to update/get the MXRoomState from room, and this function is asynchron if the MXRoomState is unknow. It is not easy to use.

When we look the Android Version, we see that the MXRoomSummary Class contain an variable with LatestRoomState. It is more usable.

This LatestRoomState come from the Matrix Android SDK, it is filled during the ReceivedEvent function.

It should be great to have the same in iOS SDK version.

**Comment by manuroe** [comment]
`MXRoomState` access is asynchronous on iOS for performance reasons. A room state can contain thousands of state events, which makes it slow to load. 
The `MXRoomSummary` purpose is to have the list of rooms as quick as possible. Including `MXRoomState` will make this list x100 times slower to get.

BUT you can add  `MXRoomState` or `canonicalAlias` to `MXRoomSummary` by yourself if your project requires it. You just need to feed `MXRoomSummary.others` with those data using the `MXRoomSummaryUpdating` delegation.

You can find an example of it in MatrixKit:
https://github.com/matrix-org/matrix-ios-kit/blob/cd38042c95c6e437d0d3b717b8106ec262c61c2c/MatrixKit/Utils/EventFormatter/MXKEventFormatter.m#L1690
